name: ci-minidb-benchmarks
on:
  push:
    branches:
      - main
      - 'release/v*'
  pull_request_target:
    branches:
      - main
      - 'release/v*'
jobs:
  badger-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Run MiniDB Benchmarks
        run: make bench
